# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - script: netstat -an | grep 3306
    displayName: 'netstat -an | grep 3306'

  - script: sudo apt-get remove mysql-server-5.7
    displayName: 'sudo apt-get remove mysql-server-5.7'
